### PR TITLE
fix(core): fix form fields query throw error

### LINKED ISSUE #3932: [Bug Report] ArrayField method will throw error and break
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/loving-wind-ylyc4y?file=/App.tsx)

### Steps to reproduce
第一步：加载10w数据
第二步：点到最后一页
第三步：点回第一页点击下面Insert键，就会崩溃

### What is expected?
无论怎么翻页，调用ArrayField的method可以正常的添加数据

### What is actually happening?
跳过中间的页面翻页，会导致前面的页面添加数据失败

### Package
@formily/core@2.2.29

---

数据的量不重要，中间跳过的页面没有加载过可能是导致错误的原因
if (field.match(_this.pattern))  这里报错
TypeError: Cannot read properties of undefined (reading 'match')

var Query = /** @class */function () {
  function Query(props) {
    var _this = this;
    this.addresses = [];
    this.pattern = _formily_shared__WEBPACK_IMPORTED_MODULE_0__.FormPath.parse(props.pattern, props.base);
    this.form = props.form;
    if (!this.pattern.isMatchPattern) {
      var matched = takeMatchPattern(this.form, this.pattern.haveRelativePattern ? (0,_shared_internals__WEBPACK_IMPORTED_MODULE_1__.buildDataPath)(props.form.fields, this.pattern) : this.pattern);
      if (matched) {
        this.addresses = [matched];
      }
    } else {
      (0,_formily_shared__WEBPACK_IMPORTED_MODULE_0__.each)(this.form.fields, function (field, address) {
        if (field.match(_this.pattern)) {
          _this.addresses.push(address);
        }
      });
    }
  }
  Query.prototype.take = function (taker) {
    return output(this.form.fields[this.addresses[0]], taker);
  };

### LINKED ISSUE #3941: [Bug Report]  Incorrect mounted Property State in Array Items After Removal
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/array-delete-issue-vy55s8?file=/App.tsx)

### Steps to reproduce
1. Remove an item from the array.
2. Observe the mounted property of the remaining array items.

array-problem

### What is expected?
After removing an item from the array, the mounted property of the remaining items should remain `true`.

### What is actually happening?
After removing an item from the array, the mounted property of the remaining items incorrectly becomes `false`.

### Package
@formily/core@2.2.29

---

This issue impacts the accurate tracking of the mounted state of array items, potentially leading to incorrect behaviours or rendering inconsistencies in complex forms.

### PR DESCRIPTION
**Pull request by janryWang**
_Before_ submitting a pull request, please make sure the following is done...

- [x] Ensure the pull request title and commit message follow the [Commit Specific](https://formilyjs.org/guide/contribution#pr-specification) in **English**.
- [x] Fork the repo and create your branch from `master` or `formily_next`.
- [x] If you've added code that should be tested, add tests!
- [ ] If you've changed APIs, update the documentation.
- [x] Ensure the test suite passes (`npm test`).
- [x] Make sure your code lints (`npm run lint`) - we've done our best to make sure these rules match our internal linting guidelines.

**Please do not delete the above content**

---

## What have you changed?

Fixed #3932

### CODE REVIEW

File: packages/core/src/models/Query.ts [hunk 1]
```diff
@@ -45,6 +45,10 @@ export class Query {
       }
     } else {
       each(this.form.fields, (field, address) => {
+        if (!field) {
```
Comment (charlzyx) [inline packages/core/src/models/Query.ts:48]: 虽然这样修复了这个问题, 但为什么不采用 https://github.com/alibaba/formily/pull/3987/files 在 undefined 产生的源头尽快修复的方案, 在这里修复有种头痛医头脚痛医脚的感觉

Comment (xiaosi-ss) [reply packages/core/src/models/Query.ts:48]: 痛哭流涕
